name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: everviolet

      - name: Install dependencies
        run: nix profile install nixpkgs#just github:everviolet/whiskers nixpkgs#zip nixpkgs#gh

      - name: Build
        run: just build

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish NPM package
        working-directory: dist
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
